In [1]:
import pandas as pd
import numpy as np


In [2]:
hr_train = pd.read_csv(r'train_hr.csv', 
                       index_col=0,header = 0)

hr_train.head()

department     region         education gender  \
employee_id                                                          
65438        Sales & Marketing   region_7  Master's & above      f   
65141               Operations  region_22        Bachelor's      m   
7513         Sales & Marketing  region_19        Bachelor's      m   
2542         Sales & Marketing  region_23        Bachelor's      m   
48945               Technology  region_26        Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [3]:
hr_train.shape

(54808, 13)

In [4]:
hr_train.drop("gender",axis=1,inplace=True)
hr_train.shape

(54808, 12)

In [5]:
hr_train.isnull().sum()

department                 0
region                     0
education               2409
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [6]:
hr_train["education"].fillna(hr_train["education"].mode()[0],inplace=True)
hr_train["previous_year_rating"].fillna(0,inplace=True)

In [7]:
hr_train["education"].mode()[0]

"Bachelor's"

In [8]:
hr_train.isnull().sum()

department              0
region                  0
education               0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [9]:
hr_train.head()

department     region         education  \
employee_id                                                   
65438        Sales & Marketing   region_7  Master's & above   
65141               Operations  region_22        Bachelor's   
7513         Sales & Marketing  region_19        Bachelor's   
2542         Sales & Marketing  region_23        Bachelor's   
48945               Technology  region_26        Bachelor's   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [10]:
colname = ['department',
          'region', 'education',
          'recruitment_channel']
colname

['department', 'region', 'education', 'recruitment_channel']

In [11]:
# For preprocessing the data
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
     hr_train[x]=le.fit_transform(hr_train[x])


In [12]:
hr_train.head()

department  region  education  recruitment_channel  \
employee_id                                                       
65438                 7      31          2                    2   
65141                 4      14          0                    0   
7513                  7      10          0                    2   
2542                  7      15          0                    0   
48945                 8      18          0                    0   

             no_of_trainings  age  previous_year_rating  length_of_service  \
employee_id                                                                  
65438                      1   35                   5.0                  8   
65141                      1   30                   5.0                  4   
7513                       1   34                   3.0                  7   
2542                       2   39                   1.0                 10   
48945                      1   45                   3.0                  2   

             KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
employee_id                                                               
65438                    1            0                  49            0  
65141                    0            0                  60            0  
7513                     0            0                  50            0  
2542                     0            0                  50            0  
48945                    0            0                  73            0

In [13]:
X = hr_train.values[:,:-1]
Y = hr_train.values[:,-1]



In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
#print(X)

In [15]:
hr_train.dtypes


department                int32
region                    int32
education                 int32
recruitment_channel       int32
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted               int64
dtype: object

In [16]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=10)  


In [17]:
import warnings
warnings.filterwarnings("ignore")

# Logistic Regression

In [18]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

print(classifier.coef_)
print(classifier.intercept_)

[[ 0.18504485  0.04224641  0.11767097  0.00992172 -0.09968157 -0.18107998
   0.31198921  0.08063322  0.65714136  0.29332285  0.63146644]]
[-2.87712162]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)



[[14994    70]
 [ 1285    94]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.57      0.07      0.12      1379

    accuracy                           0.92     16443
   macro avg       0.75      0.53      0.54     16443
weighted avg       0.89      0.92      0.89     16443

Accuracy of the model:  0.9175941129964118


# KNN

In [20]:
"""
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

for K in range(1,31):
    model_KNN = KNeighborsClassifier(K,metric="euclidean")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
"""

'\nfrom sklearn.metrics import accuracy_score\nfrom sklearn.neighbors import KNeighborsClassifier\n\nfor K in range(1,31):\n    model_KNN = KNeighborsClassifier(K,metric="euclidean")\n    model_KNN.fit(X_train, Y_train) \n    Y_pred = model_KNN.predict(X_test)\n    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)\n'

In [21]:
X_train.shape

(38365, 11)

In [22]:
hr_train.is_promoted.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [23]:
#predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=19, metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)



[[15029    35]
 [ 1255   124]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.78      0.09      0.16      1379

    accuracy                           0.92     16443
   macro avg       0.85      0.54      0.56     16443
weighted avg       0.91      0.92      0.89     16443

Accuracy of the model:  0.9215471629264733


# SVM

In [25]:
from sklearn import svm
svc_model=svm.SVC(kernel='rbf',C=1.0,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[15044    20]
 [ 1240   139]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.87      0.10      0.18      1379

    accuracy                           0.92     16443
   macro avg       0.90      0.55      0.57     16443
weighted avg       0.92      0.92      0.89     16443

Accuracy of the model:  0.9233716475095786


# Decision Trees

In [27]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[14096   968]
 [  763   616]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.95      0.94      0.94     15064
         1.0       0.39      0.45      0.42      1379

    accuracy                           0.89     16443
   macro avg       0.67      0.69      0.68     16443
weighted avg       0.90      0.89      0.90     16443

Accuracy of the model:  0.8947272395548258


# Random Forest

In [29]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)


In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[14958   106]
 [  962   417]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.94      0.99      0.97     15064
         1.0       0.80      0.30      0.44      1379

    accuracy                           0.94     16443
   macro avg       0.87      0.65      0.70     16443
weighted avg       0.93      0.94      0.92     16443

Accuracy of the model:  0.9350483488414523


# Upsampling

In [31]:
hr_train.is_promoted.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [32]:
from sklearn.utils import resample
# Separate majority and minority classes
df_majority = hr_train[hr_train.is_promoted==0]
df_minority = hr_train[hr_train.is_promoted==1]
 
# Upsample minority class
df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=50140,    # to match majority class
                                 random_state=10) # reproducible results
 
# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])
 
# Display new class counts
df_upsampled.is_promoted.value_counts()

1    50140
0    50140
Name: is_promoted, dtype: int64

In [33]:
X = df_upsampled.values[:,:-1]
Y = df_upsampled.values[:,-1]



In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
#print(X)

In [35]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=10)  


In [36]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[13955  1060]
 [    0 15069]]
Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      0.93      0.96     15015
         1.0       0.93      1.00      0.97     15069

    accuracy                           0.96     30084
   macro avg       0.97      0.96      0.96     30084
weighted avg       0.97      0.96      0.96     30084

Accuracy of the model:  0.9647653237601382


In [38]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)


In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[14410   605]
 [    0 15069]]
Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98     15015
         1.0       0.96      1.00      0.98     15069

    accuracy                           0.98     30084
   macro avg       0.98      0.98      0.98     30084
weighted avg       0.98      0.98      0.98     30084

Accuracy of the model:  0.9798896423347959
